[tools]
go = "1.26"
"go:github.com/fatih/gomodifytags" = "v1.17.0"
"go:github.com/go-delve/delve/cmd/dlv" = "v1.27.0"
"go:github.com/josharian/impl" = "v1.5.0"
"go:golang.org/x/tools/cmd/goimports" = "v0.48.0"
"go:golang.org/x/tools/gopls" = "v0.23.0"
"go:mvdan.cc/gofumpt" = "v0.11.0"
