[gmail]
source = notmuch://~/.local/share/mail/gmail
maildir-store = ~/.local/share/mail/gmail
folders-sort = Unread,Inbox,Sent,Drafts,Trash,AllUnread,Starred,Replied,Forwarded,Attachments,All
folders = Unread,Inbox,Sent,Drafts,Trash,AllUnread,Starred,Replied,Forwarded,Attachments,All

from = Quang Dang <ammon134@gmail.com>

outgoing = sendmail

default = Unread
query-map = ~/.config/aerc/gmail_queries

check-mail = 5m
check-mail-cmd = ~/.config/aerc/mail-sync
