[[profiles]]
id = 'EB33C7BE-94E3-4A01-BA31-2331F43F6C30'
name = 'Default'

[[profiles.workspaces]]
assignAppShortcut = 'opt+shift+b'
display = 'Built-in Retina Display'
id = '4B581926-1CFF-49C3-872C-78B2F5ABEDEB'
name = 'Base'
shortcut = 'opt+b'
symbolIconName = 'homekit'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.spotify.client'
iconPath = '/Applications/Spotify.app/Contents/Resources/Icon.icns'
name = 'Spotify'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.systempreferences'
iconPath = '/System/Applications/System Settings.app/Contents/Resources/PrefApp.icns'
name = 'System Settings'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.Music'
iconPath = '/System/Applications/Music.app/Contents/Resources/AppIcon.icns'
name = 'Music'

[[profiles.workspaces]]
assignAppShortcut = 'opt+shift+r'
display = 'DELL U2723QE'
id = '55D53F27-C604-4488-8E9E-ADAE976957A6'
name = 'Read'
shortcut = 'opt+r'
symbolIconName = 'book.pages'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.yellowmonkeystudio.gcal'
iconPath = '/Applications/GCal for Google Calendar.app/Contents/Resources/AppIcon.icns'
name = 'GCal for Google Calendar'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.Preview'
iconPath = '/System/Applications/Preview.app/Contents/Resources/AppIcon.icns'
name = 'Preview'

[[profiles.workspaces]]
assignAppShortcut = 'opt+shift+t'
display = 'DELL U2723QE'
id = '34631EF0-E4F8-47C3-AE94-9D7D90612ED4'
name = 'Terminal'
shortcut = 'opt+t'
symbolIconName = 'apple.terminal'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.github.wez.wezterm'
iconPath = '/Applications/WezTerm.app/Contents/Resources/terminal.icns'
name = 'WezTerm'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.jetbrains.intellij.ce'
iconPath = '/Applications/IntelliJ IDEA CE.app/Contents/Resources/idea.icns'
name = 'IntelliJ IDEA'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.microsoft.VSCode'
iconPath = '/Applications/Visual Studio Code.app/Contents/Resources/Code.icns'
name = 'Code'

[[profiles.workspaces.apps]]
bundleIdentifier = 'net.java.openjdk.java'
name = 'Mars'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.mitchellh.ghostty'
iconPath = '/Applications/Ghostty.app/Contents/Resources/Ghostty.icns'
name = 'Ghostty'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.microsoft.Word'
iconPath = '/Applications/Microsoft Word.app/Contents/Resources/Word_macOS.icns'
name = 'Microsoft Word'

[[profiles.workspaces]]
assignAppShortcut = 'opt+shift+s'
display = 'DELL U2723QE'
id = '3B9F5074-A9D9-47C4-97E2-3998321CEC95'
name = 'Browser'
shortcut = 'opt+s'
symbolIconName = 'network'

[[profiles.workspaces.apps]]
bundleIdentifier = 'company.thebrowser.Browser'
iconPath = '/Applications/Arc.app/Contents/Resources/AppIcon.icns'
name = 'Arc'

[[profiles.workspaces.apps]]
bundleIdentifier = 'app.zen-browser.zen'
iconPath = '/Applications/Zen.app/Contents/Resources/firefox.icns'
name = 'Zen'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.google.Chrome'
iconPath = '/Applications/Google Chrome.app/Contents/Resources/app.icns'
name = 'Google Chrome'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.Safari'
iconPath = '/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/Contents/Resources/AppIcon.icns'
name = 'Safari'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.microsoft.edgemac'
iconPath = '/Applications/Microsoft Edge.app/Contents/Resources/app.icns'
name = 'Microsoft Edge'

[[profiles.workspaces]]
assignAppShortcut = 'opt+shift+c'
display = 'DELL U2723QE'
id = '2E8672DD-9D93-4BEF-8358-3E8A24C826F2'
name = 'Chat'
shortcut = 'opt+c'
symbolIconName = 'message'

[[profiles.workspaces.apps]]
bundleIdentifier = 'net.whatsapp.WhatsApp'
iconPath = '/Applications/WhatsApp.app/Contents/Resources/AppIconCatalystRelease.icns'
name = "\u200EWhatsApp"

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.MobileSMS'
iconPath = '/System/Applications/Messages.app/Contents/Resources/AppIcon.icns'
name = 'Messages'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.hnc.Discord'
iconPath = '/Applications/Discord.app/Contents/Resources/electron.icns'
name = 'Discord'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.vng.zalo'
iconPath = '/Applications/Zalo.app/Contents/Resources/icon.icns'
name = 'Zalo'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.facebook.archon.developerID'
iconPath = '/Applications/Messenger.app/Contents/Resources/messenger.icns'
name = 'Messenger'

[[profiles.workspaces]]
assignAppShortcut = 'opt+shift+n'
display = 'DELL U2723QE'
id = '69B177AC-8B20-4998-BAEF-4996BD2D5D9A'
name = 'Notes'
shortcut = 'opt+n'
symbolIconName = 'note.text'

[[profiles.workspaces.apps]]
bundleIdentifier = 'md.obsidian'
iconPath = '/Applications/Obsidian.app/Contents/Resources/icon.icns'
name = 'Obsidian'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.apple.Notes'
iconPath = '/System/Applications/Notes.app/Contents/Resources/AppIcon.icns'
name = 'Notes'

[[profiles.workspaces.apps]]
bundleIdentifier = 'us.zoom.xos'
iconPath = '/Applications/zoom.us.app/Contents/Resources/ZPLogo.icns'
name = 'zoom.us'

[[profiles.workspaces]]
assignAppShortcut = 'opt+shift+z'
display = 'DELL U2723QE'
id = '2C139EE4-E41F-4A5C-A961-63D652968C6B'
name = 'Zed'
shortcut = 'opt+z'
symbolIconName = 'rectangle.and.pencil.and.ellipsis'

[[profiles.workspaces.apps]]
bundleIdentifier = 'dev.zed.Zed'
iconPath = '/Applications/Zed.app/Contents/Resources/Zed.icns'
name = 'Zed'