activeWorkspaceOnFocusChange = true
alternativeDisplays = ''
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = true
changeWorkspaceOnAppAssign = true
checkForUpdatesAutomatically = false
displayMode = 'static'
enableFocusManagement = true
enableIntegrations = false
enablePictureInPictureSupport = true
enableSpaceControl = false
enableSpaceControlAnimations = true
enableSpaceControlTilesAnimations = true
enableSwipeGestures = false
enableWorkspaceTransitions = false
focusFrontmostWindow = false
focusNextWorkspaceWindow = 'opt+]'
focusPreviousWorkspaceWindow = 'opt+['
keepUnassignedAppsOnSwitch = true
loopWorkspaces = true
loopWorkspacesOnAllDisplays = false
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE'
pipApps = []
pipScreenCornerOffset = 5
restartAppOnWakeUp = false
restoreHiddenAppsOnSwitch = false
runScriptAfterWorkspaceChange = ''
runScriptOnLaunch = ''
runScriptOnProfileChange = 'sketchybar --reload'
runScriptOnWorkspaceChange = 'sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE" DISPLAY="$DISPLAY"'
showFloatingNotifications = true
showMenuBarIcon = true
showMenuBarTitle = false
skipEmptyWorkspacesOnSwitch = false
spaceControlCurrentDisplayWorkspaces = false
spaceControlHideEmptyWorkspaces = false
spaceControlNumberOfColumns = 0
spaceControlUpdateScreenshotsOnOpen = false
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'none'
swipeLeft4FingerAction = 'previousWorkspace'
swipeRight3FingerAction = 'none'
swipeRight4FingerAction = 'nextWorkspace'
swipeThreshold = 0.25
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
switchToRecentWorkspace = 'opt+tab'
switchWorkspaceOnCursorScreen = false
switchWorkspaceWhenPipCloses = true
toggleTheFocusedAppFloating = 'opt+f'
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.29999999999999999

[[floatingApps]]
bundleIdentifier = 'us.zoom.xos'
iconPath = '/Applications/zoom.us.app/Contents/Resources/ZPLogo.icns'
name = 'zoom.us'

[[floatingApps]]
bundleIdentifier = 'com.microsoft.Word'
iconPath = '/Applications/Microsoft Word.app/Contents/Resources/Word_macOS.icns'
name = 'Microsoft Word'

[[floatingApps]]
bundleIdentifier = 'com.apple.systempreferences'
iconPath = '/System/Applications/System Settings.app/Contents/Resources/SystemSettings.icns'
name = 'System Settings'

[[floatingApps]]
bundleIdentifier = 'com.apple.finder'
iconPath = '/System/Library/CoreServices/Finder.app/Contents/Resources/Finder.icns'
name = 'Finder'