# Apply the palette declared by the sourcing theme file.
set -gx fish_color_normal $theme_foreground
set -gx fish_color_command $theme_fish_command
set -gx fish_color_keyword $theme_fish_keyword
set -gx fish_color_quote $theme_fish_quote
set -gx fish_color_redirection $theme_fish_redirection
set -gx fish_color_end $theme_fish_end
set -gx fish_color_option $theme_fish_option
set -gx fish_color_error $theme_red
set -gx fish_color_param $theme_fish_param
set -gx fish_color_comment $theme_comment
set -gx fish_color_selection "--background=$theme_selection"
set -gx fish_color_search_match "--background=$theme_selection"
set -gx fish_color_operator $theme_fish_operator
set -gx fish_color_escape $theme_fish_escape
set -gx fish_color_autosuggestion $theme_muted
set -gx fish_color_cancel $theme_red
set -gx fish_color_status $theme_red
set -gx fish_color_cwd $theme_fish_cwd
set -gx fish_color_cwd_root $theme_red
set -gx fish_color_user $theme_fish_user
set -gx fish_color_host $theme_fish_host
set -gx fish_color_host_remote $theme_fish_host_remote

set -gx fish_pager_color_progress $theme_muted
set -gx fish_pager_color_prefix $theme_cyan
set -gx fish_pager_color_completion $theme_foreground
set -gx fish_pager_color_description $theme_muted
set -gx fish_pager_color_selected_background "--background=$theme_selection"
set -gx fish_pager_color_selected_prefix $theme_cyan
set -gx fish_pager_color_selected_completion $theme_foreground
set -gx fish_pager_color_selected_description $theme_comment

# Keep tool-specific Tide brand colors, but theme the prompt structure and state.
set -gx tide_character_color $theme_green
set -gx tide_character_color_failure $theme_red
set -gx tide_cmd_duration_bg_color normal
set -gx tide_cmd_duration_color $theme_comment
set -gx tide_context_bg_color normal
set -gx tide_context_color_default $theme_yellow
set -gx tide_context_color_root $theme_orange
set -gx tide_context_color_ssh $theme_cyan
set -gx tide_direnv_bg_color normal
set -gx tide_direnv_bg_color_denied normal
set -gx tide_direnv_color $theme_orange
set -gx tide_direnv_color_denied $theme_red
set -gx tide_git_bg_color normal
set -gx tide_git_bg_color_unstable normal
set -gx tide_git_bg_color_urgent normal
set -gx tide_git_color_branch $theme_purple
set -gx tide_git_color_conflicted $theme_red
set -gx tide_git_color_dirty $theme_orange
set -gx tide_git_color_operation $theme_red
set -gx tide_git_color_staged $theme_yellow
set -gx tide_git_color_stash $theme_green
set -gx tide_git_color_untracked $theme_purple
set -gx tide_git_color_upstream $theme_green
set -gx tide_jobs_bg_color normal
set -gx tide_jobs_color $theme_green
set -gx tide_os_bg_color normal
set -gx tide_os_color $theme_foreground
set -gx tide_private_mode_bg_color normal
set -gx tide_private_mode_color $theme_purple
set -gx tide_prompt_color_frame_and_connection $theme_comment
set -gx tide_prompt_color_separator_same_color $theme_comment
set -gx tide_pwd_bg_color normal
set -gx tide_pwd_color_anchors $theme_cyan
set -gx tide_pwd_color_dirs $theme_cyan
set -gx tide_pwd_color_truncated_dirs $theme_comment
set -gx tide_shlvl_bg_color normal
set -gx tide_shlvl_color $theme_yellow
set -gx tide_status_bg_color normal
set -gx tide_status_bg_color_failure normal
set -gx tide_status_color $theme_green
set -gx tide_status_color_failure $theme_red
set -gx tide_time_bg_color normal
set -gx tide_time_color $theme_comment
set -gx tide_vi_mode_bg_color_default normal
set -gx tide_vi_mode_bg_color_insert normal
set -gx tide_vi_mode_bg_color_replace normal
set -gx tide_vi_mode_bg_color_visual normal
set -gx tide_vi_mode_color_default $theme_comment
set -gx tide_vi_mode_color_insert $theme_green
set -gx tide_vi_mode_color_replace $theme_red
set -gx tide_vi_mode_color_visual $theme_purple
